version: '3.8'
services:
  jenkins:
    build: ./jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/codespace:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-network
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:8.9-community
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - dev-network

networks:
  dev-network:

volumes:
  jenkins_home:
  sonarqube_data:
